from PIL import Image, ImageDraw, ImageFont

quote = (
    "The truest measure of care is found in the time and effort we give; "
    "for what we invest in someone’s happiness becomes the quiet foundation of our own."
)

# Image settings
width, height = 1000, 340
background_color = (245, 245, 245)
text_color = (30, 30, 30)
font_size = 32

# Create image
image = Image.new("RGB", (width, height), background_color)
draw = ImageDraw.Draw(image)

# Try to use a nice font; fallback to default
try:
    font = ImageFont.truetype("arial.ttf", font_size)
except IOError:
    font = ImageFont.load_default()

# Word wrap function
def wrap_text(text, font, max_width):
    words = text.split()
    lines = []
    line = ""
    for word in words:
        test = line + word + " "
        if font.getbbox(test)[2] < max_width:
            line = test
        else:
            lines.append(line.rstrip())
            line = word + " "
    lines.append(line.rstrip())
    return lines

lines = wrap_text(quote, font, width - 80)
y_text = 50
for line in lines:
    draw.text((50, y_text), line, fill=text_color, font=font)
    y_text += font_size + 8

# Add attribution if you wish
draw.text((50, y_text + 16), "- Generated by GitHub Copilot", fill=(100, 100, 100), font=font)

# Save image
image.save("quote_image.png")
print("Image saved as quote_image.png")